data:
    split_mode: user_entry # user # entry
    fmeval: False
    binaried_rating_thres: 0.0

train:
    learning_rate: 0.001
    seed: 2022  # random seed, usually 42 is a magic number
    weight_decay: 0.0      # weight decay for the optimizer
    tensorboard_path: ~

eval:
    batch_size: 512
    cutoff: [20]
    val_metrics: [ndcg, recall]
    val_n_epoch: 1
    test_metrics: [ndcg, recall]
    topk: 100
    save_path: './saved/'

model:
    embed_dim: 64
