model:
  hidden_size: 128
  layer_num: 2
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1e-12

  # directau
  directau_loss: True
  gamma: 0.5

train:
  negative_count: 1
  init_method: normal

data:
  test_rep: True
  train_rep: True
  split_ratio: 2
