eval:
  batch_size: 256
  cutoff: [20, 50, 10, 5]


model:
  # transformer
  hidden_size: 64
  layer_num: 2
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1e-12
  # contrastive learning
  augment_type: item_random  # item_crop, item_mask, item_reorder
  temperature: 1.0
  cl_weight: 0.1
  graph_aug: false
  k: 2
  gnn_layers: 2
  noise: 0.05
  graph_temperature: 0.2

train:
  early_stop_patience: 40
  batch_size: 256
  epochs: 1000
  init_method: normal
  negative_count: 1
  warm_up_epoches: 0 # number of epochs to start IntentCL.
