model:
  hidden_size: 256
  layer_num: 2
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1e-12
  # Graph contrastive
  k: 2
  temperature: 0.2
  cl_weight: 0.1
  mmd_weight: 0.1


train:
  batch_size: 256
  negative_count: 1
  init_method: normal
  early_stop_patience: 40
