model:
  hidden_size: 256
  layer_num: 2
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1e-12
  # Graph contrastive
  k: 2
  gnn: 'wlgn'
  gnn_layers: 2
  noise: 0.05
  temperature: 0.2
  cl_weight: 0

train:
  batch_size: 256
  negative_count: 1
  init_method: normal
